---
- name: Setup application and database servers
  hosts: all
  become: true
  vars:
    postgres_data_dir: "{{ postgres_data_dir }}"
    postgres_version: "{{ postgres_version }}"
  roles:
    - name: docker
      hosts: app
    - name: postgresql
      hosts: database

