---
- name: Setup application and database servers
  hosts: all
  become: true
  roles:
    - role: docker
      when: inventory_hostname == 'app'

    - role: postgresql
      when: inventory_hostname == 'database'
