- name: Install Docker on Ubuntu
  become: true
  apt:
    name: docker.io
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install Docker on CentOS
  become: true
  yum:
    name: docker
    state: present
  when: ansible_distribution == 'CentOS'

- name: Start Docker service on Ubuntu
  become: true
  service:
    name: docker
    state: started
  when: ansible_distribution == 'Ubuntu'

- name: Start Docker service on CentOS
  become: true
  service:
    name: docker
    state: started
  when: ansible_distribution == 'CentOS'
