---
# tasks file for postgres
- name: Install PostgreSQL
  apt:
    name: "postgresql-{{ postgres_version }}"
    state: present

- name: Start PostgreSQL service
  service:
    name: postgresql
    state: started
    enabled: yes
