- name: Install Postgres
  hosts: database
  become: true
  vars:
    postgres_data_dir: "{{ postgres_data_dir }}"
    postgres_version: "{{ postgres_version }}"
  tasks:
    - name: Install Postgres
      apt:
        name: "postgresql-{{ postgres_version }}"
        state: present
      become: true

    - name: Create data dir
      file:
        path: "{{ postgres_data_dir }}"
        state: directory
        owner: postgres
        group: postgres
        mode: '0700'
      become: true

    - name: Run  PostgreSQL Service
      systemd:
        name: postgresql
        state: started
      become: true
